---
- name: copy dist backend folder to ec2 server
  become: yes
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf backend.tar.gz -C .
- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start